name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add upstream remote
        run: git remote add upstream https://github.com/Togashiteam/portifolio

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Rebase with upstream/main
        run: git rebase upstream/main

      - name: Push changes to fork
        run: |
          git push origin HEAD:main
